name: ci

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      
      - name: Install Dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/main.py
          standalone: true
          enable-plugins: pyqt5
          disable-console: true
          include-qt-plugins: sensible,styles
          output-dir: dist
          windows-icon-from-ico: src/assets/favicon.ico
          include-data-dir: src/assets=assets

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/main.exe