name: ci-flow

on:
  push:
    branches:
      - 'gui'
  workflow_dispatch:

# env:
#   SERVER_DIR: /home/reemo-blog

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install npm deps
        run: |
          yarn 
          yarn build-linux
      - name: Archive built files
        uses: actions/upload-artifact@v3
        with:
          name: build_ubuntu_pkg
          path: deploy
        